import os

GPT_MODEL = os.environ.get("GPT_MODEL", "gpt-5.4")
IMAGE_MODEL = os.environ.get("IMAGE_MODEL", "gemini-3.1-flash-image-preview")

MODEL_CATALOG = [
    {"id": "gpt-astra", "label": "GPT Astra", "provider": "openai", "model": "gpt-6-astra",
     "tagline": "Paling cerdas untuk tugas kompleks", "accent": "#7C3AED"},
    {"id": "gpt-luna", "label": "GPT Luna", "provider": "openai", "model": "gpt-6-luna",
     "tagline": "Seimbang, kreatif & ekspresif", "accent": "#2F6BFF"},
    {"id": "gpt-terra", "label": "GPT Terra", "provider": "openai", "model": "gpt-5.6-terra",
     "tagline": "Cepat & efisien untuk harian", "accent": "#22B8FF"},
    {"id": "gpt-5-5", "label": "GPT 5.5", "provider": "openai", "model": "gpt-5.5",
     "tagline": "Generasi sebelumnya, stabil & hemat", "accent": "#60A5FA"},
    {"id": "claude-opus-5-5", "label": "Claude Opus 5.5", "provider": "anthropic", "model": "claude-opus-5-5",
     "tagline": "Flagship Anthropic — reasoning terdalam", "accent": "#D97706"},
    {"id": "claude-sonnet", "label": "Claude Sonnet 5.5", "provider": "anthropic", "model": "claude-sonnet-5-5",
     "tagline": "Penulisan & analisis mendalam", "accent": "#F59E0B"},
    {"id": "claude-opus-5", "label": "Claude Opus 5", "provider": "anthropic", "model": "claude-opus-5",
     "tagline": "Opus generasi 5, sangat teliti", "accent": "#B45309"},
    {"id": "claude-sonnet-5", "label": "Claude Sonnet 5", "provider": "anthropic", "model": "claude-sonnet-5",
     "tagline": "Sonnet generasi 5, seimbang", "accent": "#FBBF24"},
    {"id": "claude-opus-4-8", "label": "Claude Opus 4.8", "provider": "anthropic", "model": "claude-opus-4-8",
     "tagline": "Coding & agentic yang matang", "accent": "#92400E"},
    {"id": "claude-haiku", "label": "Claude Haiku 4.5", "provider": "anthropic", "model": "claude-haiku-4-5-20251001",
     "tagline": "Sangat cepat & ringan", "accent": "#FCD34D"},
    {"id": "claude-fable", "label": "Claude Fable 5.1", "provider": "anthropic", "model": "claude-fable-5-1",
     "tagline": "Kreatif untuk cerita & naskah", "accent": "#F97316"},
    {"id": "gemini-pro", "label": "Gemini 3.1 Pro", "provider": "gemini", "model": "gemini-3.1-pro-preview",
     "tagline": "Multimodal & reasoning kuat", "accent": "#10B981"},
    {"id": "gemini-3-8-flash", "label": "Gemini 3.8 Flash", "provider": "gemini", "model": "gemini-3.8-flash",
     "tagline": "Flash terbaru, cepat & cerdas", "accent": "#059669"},
    {"id": "gemini-3-7-flash", "label": "Gemini 3.7 Flash", "provider": "gemini", "model": "gemini-3.7-flash",
     "tagline": "Flash cepat untuk tugas harian", "accent": "#34D399"},
    {"id": "gemini-3-6-flash", "label": "Gemini 3.6 Flash", "provider": "gemini", "model": "gemini-3.6-flash",
     "tagline": "Flash hemat dengan konteks besar", "accent": "#6EE7B7"},
    {"id": "gemini-3-5-flash", "label": "Gemini 3.5 Flash", "provider": "gemini", "model": "gemini-3.5-flash",
     "tagline": "Cepat, hemat & multimodal", "accent": "#2DD4BF"},
    {"id": "gemini-3-flash", "label": "Gemini 3 Flash", "provider": "gemini", "model": "gemini-3-flash-preview",
     "tagline": "Flash generasi 3", "accent": "#14B8A6"},
]
